on:
  pull_request:
  issues:
    types:
      - opened
jobs:
  add-to-project:
    name: Add issue to project
    if: github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/issues.yml
    secrets:
      private-key: ${{ secrets.ISSUES_BOT_KEY }}
      app-id: ${{ secrets.ISSUES_BOT_ID }}
